### ISSUE TITLE
Is use of saltwater_internal_rst broken?

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSgcm_App#188]
A user had a set of restarts that included saltwater_internal_rst and was reporting a crash. A brief investigation shows that indeed with the 1.3.11 version of GEOSgcm_App used by v10.17 of the GEOSgcm fixture, that the use of the saltwater_internal_rst appears to be broken.

The issue is that the gcm_run.j script never copies it to scratch so it can't get split...

I verified that if I added a copy of saltwater_internal_rst to scratch the splitter seemed to work fine and the model ran without incident. 

Looking at the gcm_run.j script it looks like it gets the list of restarts to copy over by looking for _RESTART_FILE in the AGCM.rc. I'm wondering if even after we went to the split saltwater we kept saltwater_internal_rst in the AGCM.rc file so it would be copied if it existed? Maybe we removed this with unintended consequences? I can't really think of how else this would have worked in the past. Perhaps we need a manual check for saltwater_internal_rst?
Or remove the splitter logic if we don't support that but I'm assuming we still want to?

**Comment by mathomp4** [comment]
The answer is...yes it looks like. I strolled around the GitHub history and found this:
https://github.com/GEOS-ESM/GEOSgcm_App/commit/01486eb256239d3370764370211011c8777c342a
In that commit @sanAkel says:

> Replace `EXPDIR` with `SCRDIR` for EMIP to work as well.

So I guess we fixed the EMIP but had the side effect of breaking the AMIP. I think back in the CVS days when this change occurred @lltakacs and I figured that the only thing that mattered was that the `$SCRDIR` had `openwater_internal_rst` and `seaicethermo_internal_rst`. I think that's why `saltwater_internal_rst` was removed from `AGCM.rc.tmpl` because it isn't required (or wanted) anymore.

Thus these lines:
```csh
if ( ( -e $EXPDIR/saltwater_internal_rst ) && ( $counter == 1 ) ) then

   # The splitter script requires an OutData directory
   # -------------------------------------------------
   if (! -d OutData ) mkdir -p OutData

   # Run the script
   # --------------
   $RUN_CMD 1 $GEOSBIN/SaltIntSplitter tile.data $EXPDIR/saltwater_internal_rst

   # Move restarts
   # -------------
   /bin/mv OutData/openwater_internal_rst OutData/seaicethermo_internal_rst .
```
worked because we ran `SaltIntSplitter` from `$SCRDIR` on the restarts in `$EXPDIR`. The splitter ran and its output was in `OutData` and we moved the `openwater_internal_rst` and `seaicethermo_internal_rst` to `.` which is `$SCRDIR` at this point. And after that, `GEOSgcm.x` would never make a `saltwater_internal_rst` and we'd be fine. 

But apparently this was not good for EMIPs with a `saltwater_internal_rst`. I'm thinking our best strategy might be to have something like:
```csh
if ( (-e $SCRDIR/openwater_internal_rst) && (-e $SCRDIR/seaicethermo_internal_rst)) then
  echo "Saltwater internal state is already split, good to go!"
else
 if ( ( ( -e $SCRDIR/saltwater_internal_rst ) || ( -e $EXPDIR/saltwater_internal_rst) ) && ( $counter == 1 ) ) then

   if ( -e $EXPDIR/saltwater_internal_rst) cp $EXPDIR/saltwater_internal_rst .

   # The splitter script requires an OutData directory
   # -------------------------------------------------
   if (! -d OutData ) mkdir -p OutData

   # Run the script
   # --------------
   $RUN_CMD 1 $GEOSBIN/SaltIntSplitter tile.data $SCRDIR/saltwater_internal_rst
```
That is, test if you have `saltwater_internal` in `$SCRDIR` or in `$EXPDIR` and if it's in `$EXPDIR` copy into `$SCRDIR`.

I'll work on testing this and getting it working.

**Comment by sanAkel** [comment]
@mathomp4 that modification o logic for EMIP to work was worked out with @sdrabenh. He already had the split internal states, yet the script was looking was saltwater internal restart.

Our first (original) fix was for $SCRATCH set up when @yvikhlya was inadvertently using a salt water internal over and again in the middle of a _long_ climate run: shocking it! 

Maybe this is for later. How difficult is it generate a list of restarts? That works for all instances of the GCM?

**Comment by yvikhlya** [comment]
The model does not need saltwater_internal_rst since long ago. If somebody wants to run with old saltwater internal restart, they need to convert it to open_water and seaice_thermo. This is a pre-processing step which needs to be done once. I don't really understand why this logic was put into a run script. Do we really need to do it every time we submit gcm_run.j?

**Comment by mathomp4** [comment]
@yvikhlya It was for convenience during the days of the split transition. But, as a user found out just a couple days ago, some want to use old restarts that while old, are still "valid" for the boundary conditions being used.

The reason we never saw this until this is that `regrid.pl` autosplits MERRA-2 now, so anyone regridding new restarts is safe.

Luckily, 99%+ of all users will be in the first "openwater and seaicethermo" exist case.
